-- DELETE RPG GAME DATABASE
-- CASEY CULP

DROP TABLE PLAYER;
DROP TABLE CHARACTERS;
DROP TABLE CHARACTER_RACE;
DROP TABLE CHARACTER_ROLE;
DROP TABLE FACTION;
DROP TABLE ABILITY;

DROP PROCEDURE spCHANGENAME;
DROP PROCEDURE spCHANGE_ABIL_DESC;
DROP PROCEDURE spCHANGE_EXP;
DROP PROCEDURE spNEWCHAR;
DROP PROCEDURE spNEWROLE;
DROP PROCEDURE spNEWPLAYER;
DROP PROCEDURE spDELPLAYER;
DROP PROCEDURE spDELCHAR;
DROP PROCEDURE spDELROLE;

